
spring:
  datasource:
    druid:  # MySQL连接信息
      url: jdbc:mysql://localhost:3306/course?characterEncoding=utf-8&serverTimezone=GMT
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      db-type:  com.alibaba.druid.pool.DruidDataSource  #数据源类别
      initial-size: 5 #初始化大小，最小，最大
      min-idle:  5
      max-active: 20
      max-wait:  6000  #配置获取连接等待超时的时间，单位是毫秒
      time-between-connect-error-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 400000  #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query:  SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true  #打开 PS Cache ，并且指定每个连接上 PSCache 的大小
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat, wall , log4j   #＃配置监控统计拦截的 filters ，去掉后监控界面的 SQL 无法统计， wall 用于防火墙
      use-global-data-source-stat:  true  #合并多个 Dru dDataSource 的监控数据
      connect-properties:    #通过 connectProperties 属性来打开 mergeSql 功能，慢 SQL 记录
        druid.stat.mergeSql: true
        druid.stat.slowSqlMillis: 500
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: admin
  redis:
    port:  6379
    password:
    host: 127.0.0.1
    #client-name: course_reids
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
#配置log扫描的包地址
logging:
  level:
   com:
     videos:
       course:
         server:
           mapper: trace

