server:
  port: 9000
spring:
  application:
    name: getaway

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka