server:
  port: 9000
spring:
  application:
    name: getaway
  cloud:
    gateway:
      routes:
        - id: system
          uri: lb://SYSTEM  # http://127.0.0.1:9001
          predicates:
            - Path=/system/**


        - id: customer
          uri: http://127.0.0.1:9002
          predicates:
            - Path=/customer/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka